name: Verify CI

on:
    pull_request:
        branches:
          - 'master'
          - 'dev'

jobs:
  call_workflow:
    uses: ezequielrickert/ingsis-library/.github/workflows/on-pull-request.yml@main