name: Verify CI

on:
    push:
        branches:
          - '*'
    pull_request:
        branches:
          - 'master'

jobs:
  call_workflow:
    uses: ezequielrickert/ingsis-library/.github/workflows/release-package.yml@main

  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}