name: Verify CI

on:
    push:
        branches:
          - '*'
    pull_request:
        branches:
          - 'master'

jobs:
  call_workflow:
    uses: ezequielrickert/ingsis-library/.github/workflows/release-package.yml@main